### ISSUE TITLE
Specify custom location of secret files

### ISSUE THREAD

**Issue by joncursi** [serverless/serverless-secrets-plugin#5]
I don't like my project root getting full of miscellaneous files. Is it possible to specify a custom location where the secrets are, and the option to use `stage` on the folder structure rather than the file name? I.e.

```
config/
  development
    secrets.yml
    secrets.yml.encrypted
  staging
    secrets.yml
    secrets.yml.encrypted
  production
    secrets.yml
    secrets.yml.encrypted
```

**Comment by joncursi** [comment]
Looks like a PR exists for this already. https://github.com/serverless/serverless-secrets-plugin/pull/4 Can we merge?

**Comment by nikgraf** [comment]
Should be solved with this PR https://github.com/serverless/serverless-secrets-plugin/pull/2
